# Generated by Django 5.2.7 on 2025-10-15 05:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attested_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attested_by_position', models.CharField(blank=True, max_length=100, null=True)),
                ('attested_by_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('noted_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('noted_by_position', models.CharField(blank=True, max_length=100, null=True)),
                ('noted_by_signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeasedPropertyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('proponent_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_status', models.CharField(blank=True, max_length=100, null=True)),
                ('land_classification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('title_no', models.IntegerField(blank=True, null=True)),
                ('lot_no', models.IntegerField(blank=True, null=True)),
                ('lot_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_covered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pa_management_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('easement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PermitsDENREMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamb_resolution', models.BooleanField(default=False)),
                ('pamb_resolution_no', models.IntegerField(blank=True, null=True)),
                ('pamb_di', models.DateField(blank=True, null=True)),
                ('sapa', models.BooleanField(default=False)),
                ('sapa_no', models.IntegerField(blank=True, null=True)),
                ('sapa_di', models.DateField(blank=True, null=True)),
                ('pacbrma', models.BooleanField(default=False)),
                ('pacbrma_no', models.IntegerField(blank=True, null=True)),
                ('pacbrma_di', models.DateField(blank=True, null=True)),
                ('ecc', models.BooleanField(default=False)),
                ('ecc_no', models.IntegerField(blank=True, null=True)),
                ('ecc_di', models.DateField(blank=True, null=True)),
                ('discharge_permit', models.BooleanField(default=False)),
                ('dp_no', models.IntegerField(blank=True, null=True)),
                ('dp_di', models.DateField(blank=True, null=True)),
                ('permit_to_operate', models.BooleanField(default=False)),
                ('pto_no', models.IntegerField(blank=True, null=True)),
                ('pto_di', models.DateField(blank=True, null=True)),
                ('emb_rp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitsLGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayors_permit', models.BooleanField(default=False)),
                ('mp_number', models.IntegerField(blank=True, null=True)),
                ('mpdi', models.DateField(blank=True, null=True)),
                ('mped', models.DateField(blank=True, null=True)),
                ('business_permit', models.BooleanField(default=False)),
                ('bp_number', models.IntegerField(blank=True, null=True)),
                ('bpdi', models.DateField(blank=True, null=True)),
                ('bped', models.DateField(blank=True, null=True)),
                ('building_permit', models.BooleanField(default=False)),
                ('bldg_number', models.IntegerField(blank=True, null=True)),
                ('bldgdi', models.DateField(blank=True, null=True)),
                ('bldged', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('PENRO', 'PENRO'), ('CENRO', 'CENRO'), ('EVALUATOR', 'Evaluator')], default='ADMIN', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeoTaggedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorsTrackRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.geotaggedimage')),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnumeratorsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.attestationnotation')),
                ('geo_tag_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.geotaggedimage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.leasedpropertyprofile')),
                ('denr_emb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.permitsdenremb')),
                ('lgu_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DENRO.permitslgu')),
                ('pa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.protectedarea')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DENRO.typeofestablishment')),
                ('enumerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerator_reports', to=settings.AUTH_USER_MODEL)),
                ('informant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informant_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ERROR', 'Error'), ('REPORT_CENRO', 'CENRO Report'), ('REPORT_PENRO', 'PENRO Report')], max_length=16)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='DENRO_activ_created_dd9a26_idx'), models.Index(fields=['action'], name='DENRO_activ_action_18ce2b_idx'), models.Index(fields=['user'], name='DENRO_activ_user_id_557f94_idx')],
            },
        ),
    ]
