# Generated by Django 5.2.7 on 2025-10-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DENRO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='attestation',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='denr_emb',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='enumerator',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='geo_tag_image',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='informant',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='lgu_permit',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='pa',
        ),
        migrations.RemoveField(
            model_name='enumeratorsreport',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='evaluatorstrackroute',
            name='captured_by',
        ),
        migrations.RemoveField(
            model_name='evaluatorstrackroute',
            name='pointer',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='captured_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='AttestationNotation',
        ),
        migrations.DeleteModel(
            name='PermitsDENREMB',
        ),
        migrations.DeleteModel(
            name='TypeOfEstablishment',
        ),
        migrations.DeleteModel(
            name='PermitsLGU',
        ),
        migrations.DeleteModel(
            name='ProtectedArea',
        ),
        migrations.DeleteModel(
            name='EnumeratorsReport',
        ),
        migrations.DeleteModel(
            name='LeasedPropertyProfile',
        ),
        migrations.DeleteModel(
            name='EvaluatorsTrackRoute',
        ),
        migrations.DeleteModel(
            name='GeoTaggedImage',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
